// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dJqK6LEBeKixAKagJBAmzL
// Component: DybXCSmk6J

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_iddr.module.css"; // plasmic-import: dJqK6LEBeKixAKagJBAmzL/projectcss
import sty from "./PlasmicNetworkCard.module.css"; // plasmic-import: DybXCSmk6J/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: iDs7aDQs7T/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: ZLscOeex6V/icon

export type PlasmicNetworkCard__VariantMembers = {};
export type PlasmicNetworkCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicNetworkCard__VariantsArgs;
export const PlasmicNetworkCard__VariantProps = new Array<VariantPropType>();

export type PlasmicNetworkCard__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicNetworkCard__ArgsType;
export const PlasmicNetworkCard__ArgProps = new Array<ArgPropType>("children");

export type PlasmicNetworkCard__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultNetworkCardProps {
  children?: React.ReactNode;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNetworkCard__RenderFunc(props: {
  variants: PlasmicNetworkCard__VariantsArgs;
  args: PlasmicNetworkCard__ArgsType;
  overrides: PlasmicNetworkCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <p.Stack
              as={p.PlasmicLink}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__h8Asd
              )}
              component={Link}
              platform={"nextjs"}
            >
              <Icon3Icon
                className={classNames(projectcss.all, sty.svg__xt0V2)}
                role={"img"}
              />

              <h5
                className={classNames(
                  projectcss.all,
                  projectcss.h5,
                  projectcss.__wab_text,
                  sty.h5__cAdKg
                )}
              >
                {"BSC"}
              </h5>
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__mcgrt)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dTpuR
                    )}
                  >
                    {"Open Eplorer"}
                  </div>
                  <Icon8Icon
                    className={classNames(projectcss.all, sty.svg__s3YMw)}
                    role={"img"}
                  />
                </div>
              ) : null}
            </p.Stack>
          ),
          value: args.children
        })}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNetworkCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNetworkCard__VariantsArgs;
    args?: PlasmicNetworkCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNetworkCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNetworkCard__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNetworkCard__ArgProps,
          internalVariantPropNames: PlasmicNetworkCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNetworkCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNetworkCard";
  } else {
    func.displayName = `PlasmicNetworkCard.${nodeName}`;
  }
  return func;
}

export const PlasmicNetworkCard = Object.assign(
  // Top-level PlasmicNetworkCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNetworkCard
    internalVariantProps: PlasmicNetworkCard__VariantProps,
    internalArgProps: PlasmicNetworkCard__ArgProps
  }
);

export default PlasmicNetworkCard;
/* prettier-ignore-end */
