// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dJqK6LEBeKixAKagJBAmzL
// Component: ThJz7UjPOLc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsvWlfn14Jm89In } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: vWLFN14Jm89IN/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_iddr.module.css"; // plasmic-import: dJqK6LEBeKixAKagJBAmzL/projectcss
import sty from "./PlasmicNavbar.module.css"; // plasmic-import: ThJz7UjPOLc/css

import MenuSvgrepoComsvgIcon from "./icons/PlasmicIcon__MenuSvgrepoComsvg"; // plasmic-import: XTdEHy648t/icon
import CloseBoldSvgrepoComsvgIcon from "./icons/PlasmicIcon__CloseBoldSvgrepoComsvg"; // plasmic-import: 3wjTpps_Fo/icon
import CmcsvgIcon from "./icons/PlasmicIcon__Cmcsvg"; // plasmic-import: n_1Fj4QpLk/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: V54Kju9r17/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: lDkdlle9aD/icon

export type PlasmicNavbar__VariantMembers = {};
export type PlasmicNavbar__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavbar__VariantsArgs;
export const PlasmicNavbar__VariantProps = new Array<VariantPropType>();

export type PlasmicNavbar__ArgsType = {
  isMenuOpen?: boolean;
  onIsMenuOpenChange?: (val: boolean) => void;
};
type ArgPropType = keyof PlasmicNavbar__ArgsType;
export const PlasmicNavbar__ArgProps = new Array<ArgPropType>(
  "isMenuOpen",
  "onIsMenuOpenChange"
);

export type PlasmicNavbar__OverridesType = {
  navbar?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  menus?: p.Flex<"div">;
  mnItem?: p.Flex<"a"> & Partial<LinkProps>;
  mnItem2?: p.Flex<"a"> & Partial<LinkProps>;
  mnItem3?: p.Flex<"a"> & Partial<LinkProps>;
  mnItem4?: p.Flex<"a"> & Partial<LinkProps>;
  cmc?: p.Flex<"a"> & Partial<LinkProps>;
  telegram?: p.Flex<"a"> & Partial<LinkProps>;
  twitter?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultNavbarProps {
  isMenuOpen?: boolean;
  onIsMenuOpenChange?: (val: boolean) => void;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbar__RenderFunc(props: {
  variants: PlasmicNavbar__VariantsArgs;
  args: PlasmicNavbar__ArgsType;
  overrides: PlasmicNavbar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "isMenuOpen",
        type: "writable",
        variableType: "boolean",

        valueProp: "isMenuOpen",
        onChangeProp: "onIsMenuOpenChange"
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsvWlfn14Jm89In()
  });

  return (
    <div
      data-plasmic-name={"navbar"}
      data-plasmic-override={overrides.navbar}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.navbar
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__wvXmR)}>
        <p.PlasmicLink
          className={classNames(projectcss.all, projectcss.a, sty.link___85NvS)}
          component={Link}
          platform={"nextjs"}
        >
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"42px" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            loading={"lazy" as const}
            src={{
              src: "/plasmic/iddr/images/iddrLandscape1Png.png",
              fullWidth: 904,
              fullHeight: 251,
              aspectRatio: undefined
            }}
          />
        </p.PlasmicLink>
        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"menus"}
            data-plasmic-override={overrides.menus}
            hasGap={true}
            className={classNames(projectcss.all, sty.menus)}
          >
            <p.PlasmicLink
              data-plasmic-name={"mnItem"}
              data-plasmic-override={overrides.mnItem}
              className={classNames(projectcss.all, projectcss.a, sty.mnItem)}
              component={Link}
              href={"#home" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__doFl
                )}
              >
                {"Beranda"}
              </div>
            </p.PlasmicLink>
            <p.PlasmicLink
              data-plasmic-name={"mnItem2"}
              data-plasmic-override={overrides.mnItem2}
              className={classNames(projectcss.all, projectcss.a, sty.mnItem2)}
              component={Link}
              href={"#about" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__diLvd
                )}
              >
                {"Tentang"}
              </div>
            </p.PlasmicLink>
            <p.PlasmicLink
              data-plasmic-name={"mnItem3"}
              data-plasmic-override={overrides.mnItem3}
              className={classNames(projectcss.all, projectcss.a, sty.mnItem3)}
              component={Link}
              href={"#team" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j8Gj
                )}
              >
                {"Tim"}
              </div>
            </p.PlasmicLink>
            <p.PlasmicLink
              data-plasmic-name={"mnItem4"}
              data-plasmic-override={overrides.mnItem4}
              className={classNames(projectcss.all, projectcss.a, sty.mnItem4)}
              component={Link}
              href={"#contact" as const}
              platform={"nextjs"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iudxA
                )}
              >
                {"Kontak"}
              </div>
            </p.PlasmicLink>
          </p.Stack>
        ) : null}
        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <p.PlasmicLink
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__dInIj
            )}
            component={Link}
            onClick={async event => {
              const $steps = {};
              $steps["updateIsMenuOpen"] = true
                ? (() => {
                    const actionArgs = {
                      variable: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "updateVariable",
                          interactionUuid: "LBkPAXwzI",
                          componentUuid: "ThJz7UjPOLc",
                          argName: "variable"
                        },
                        () => ({
                          objRoot: $state,
                          variablePath: ["isMenuOpen"]
                        })
                      ),
                      operation: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "updateVariable",
                          interactionUuid: "LBkPAXwzI",
                          componentUuid: "ThJz7UjPOLc",
                          argName: "operation"
                        },
                        () => 4
                      )
                    };
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "updateVariable",
                        interactionUuid: "LBkPAXwzI",
                        componentUuid: "ThJz7UjPOLc"
                      },
                      () =>
                        (({ variable, value, startIndex, deleteCount }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          const oldValue = p.get(objRoot, variablePath);
                          p.set(objRoot, variablePath, !oldValue);
                          return !oldValue;
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["updateIsMenuOpen"] === "object" &&
                typeof $steps["updateIsMenuOpen"].then === "function"
              ) {
                $steps["updateIsMenuOpen"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "updateVariable",
                    interactionUuid: "LBkPAXwzI",
                    componentUuid: "ThJz7UjPOLc"
                  },
                  $steps["updateIsMenuOpen"]
                );
              }
            }}
            platform={"nextjs"}
          >
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <MenuSvgrepoComsvgIcon
                className={classNames(projectcss.all, sty.svg__dMoHh)}
                role={"img"}
              />
            ) : null}
          </p.PlasmicLink>
        ) : null}
        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <p.PlasmicLink
            className={classNames(
              projectcss.all,
              projectcss.a,
              sty.link__agVnM
            )}
            component={Link}
            platform={"nextjs"}
          >
            <CloseBoldSvgrepoComsvgIcon
              className={classNames(projectcss.all, sty.svg__al8He)}
              role={"img"}
            />
          </p.PlasmicLink>
        ) : null}
        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__rxuxc)}
          >
            <p.PlasmicLink
              data-plasmic-name={"cmc"}
              data-plasmic-override={overrides.cmc}
              className={classNames(projectcss.all, projectcss.a, sty.cmc)}
              component={Link}
              href={
                "https://coinmarketcap.com/currencies/idr-digital/" as const
              }
              platform={"nextjs"}
              target={"_blank" as const}
            >
              <CmcsvgIcon
                className={classNames(projectcss.all, sty.svg__j8Hg9)}
                role={"img"}
              />
            </p.PlasmicLink>
            <p.PlasmicLink
              data-plasmic-name={"telegram"}
              data-plasmic-override={overrides.telegram}
              className={classNames(projectcss.all, projectcss.a, sty.telegram)}
              component={Link}
              href={"https://t.me/iddr_io" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              <IconIcon
                className={classNames(projectcss.all, sty.svg___4U4SS)}
                role={"img"}
              />
            </p.PlasmicLink>
            <p.PlasmicLink
              data-plasmic-name={"twitter"}
              data-plasmic-override={overrides.twitter}
              className={classNames(projectcss.all, projectcss.a, sty.twitter)}
              component={Link}
              href={"https://twitter.com/iddr_io" as const}
              platform={"nextjs"}
              target={"_blank" as const}
            >
              <Icon2Icon
                className={classNames(projectcss.all, sty.svg___5Sopt)}
                role={"img"}
              />
            </p.PlasmicLink>
          </p.Stack>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navbar: [
    "navbar",
    "img",
    "menus",
    "mnItem",
    "mnItem2",
    "mnItem3",
    "mnItem4",
    "cmc",
    "telegram",
    "twitter"
  ],
  img: ["img"],
  menus: ["menus", "mnItem", "mnItem2", "mnItem3", "mnItem4"],
  mnItem: ["mnItem"],
  mnItem2: ["mnItem2"],
  mnItem3: ["mnItem3"],
  mnItem4: ["mnItem4"],
  cmc: ["cmc"],
  telegram: ["telegram"],
  twitter: ["twitter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  navbar: "div";
  img: typeof p.PlasmicImg;
  menus: "div";
  mnItem: "a";
  mnItem2: "a";
  mnItem3: "a";
  mnItem4: "a";
  cmc: "a";
  telegram: "a";
  twitter: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbar__VariantsArgs;
    args?: PlasmicNavbar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavbar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavbar__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNavbar__ArgProps,
          internalVariantPropNames: PlasmicNavbar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navbar") {
    func.displayName = "PlasmicNavbar";
  } else {
    func.displayName = `PlasmicNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbar = Object.assign(
  // Top-level PlasmicNavbar renders the root element
  makeNodeComponent("navbar"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    menus: makeNodeComponent("menus"),
    mnItem: makeNodeComponent("mnItem"),
    mnItem2: makeNodeComponent("mnItem2"),
    mnItem3: makeNodeComponent("mnItem3"),
    mnItem4: makeNodeComponent("mnItem4"),
    cmc: makeNodeComponent("cmc"),
    telegram: makeNodeComponent("telegram"),
    twitter: makeNodeComponent("twitter"),

    // Metadata about props expected for PlasmicNavbar
    internalVariantProps: PlasmicNavbar__VariantProps,
    internalArgProps: PlasmicNavbar__ArgProps
  }
);

export default PlasmicNavbar;
/* prettier-ignore-end */
