// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dJqK6LEBeKixAKagJBAmzL
// Component: S-EPZS57Iq32

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: T1KJa5bGl4Ip-/codeComponent
import Navbar from "../../Navbar"; // plasmic-import: ThJz7UjPOLc/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import Button2 from "../../Button2"; // plasmic-import: R7FQakg198I/component
import NetworkCard from "../../NetworkCard"; // plasmic-import: DybXCSmk6J/component
import { DataProvider } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: D4RbnlpRXg3/codeComponent
import { RichList } from "@plasmicpkgs/plasmic-rich-components"; // plasmic-import: Hh2OL1EveIF/codeComponent
import { Embed } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: PKldDYkH42/codeComponent
import MenuOverlay from "../../MenuOverlay"; // plasmic-import: l7JCXcEFvGg/component

import { useScreenVariants as useScreenVariantsvWlfn14Jm89In } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: vWLFN14Jm89IN/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_iddr.module.css"; // plasmic-import: dJqK6LEBeKixAKagJBAmzL/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: S-EPZS57Iq32/css

import GoogleDocsSvgrepoComsvgIcon from "./icons/PlasmicIcon__GoogleDocsSvgrepoComsvg"; // plasmic-import: IYcwKk4Nul/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: g3M_pomcN7I/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: WhOp2OsiY-D/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: ljio8ldcWK/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: ZLscOeex6V/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: iDs7aDQs7T/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: fM-swEdfd/icon
import CmcsvgIcon from "./icons/PlasmicIcon__Cmcsvg"; // plasmic-import: n_1Fj4QpLk/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: V54Kju9r17/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: lDkdlle9aD/icon
import CloseBoldSvgrepoComsvgIcon from "./icons/PlasmicIcon__CloseBoldSvgrepoComsvg"; // plasmic-import: 3wjTpps_Fo/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  pageMetadataOverride?: p.Flex<typeof PlasmicHead>;
  navbar?: p.Flex<typeof Navbar>;
  h3?: p.Flex<"h3">;
  title?: p.Flex<"div">;
  desc?: p.Flex<"div">;
  desc2?: p.Flex<"div">;
  desc3?: p.Flex<"div">;
  desc4?: p.Flex<"div">;
  title3?: p.Flex<"div">;
  dataProvider?: p.Flex<typeof DataProvider>;
  dataList?: p.Flex<typeof RichList>;
  title2?: p.Flex<"div">;
  embedHtml?: p.Flex<typeof Embed>;
  cmc?: p.Flex<"a"> & Partial<LinkProps>;
  telegram?: p.Flex<"a"> & Partial<LinkProps>;
  twitter?: p.Flex<"a"> & Partial<LinkProps>;
  menuOverlay?: p.Flex<typeof MenuOverlay>;
};

export interface DefaultHomepageProps {}

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "navbar.isMenuOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsvWlfn14Jm89In()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <PlasmicHead
            data-plasmic-name={"pageMetadataOverride"}
            data-plasmic-override={overrides.pageMetadataOverride}
            className={classNames("__wab_instance", sty.pageMetadataOverride)}
            description={"Inovasi mata uang digital Nusantara"}
            image={"/plasmic/iddr/images/iddrRoundedjpg.jpg"}
            title={"Indonesia Digital Rupiah"}
          />

          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
            isMenuOpen={p.generateStateValueProp($state, [
              "navbar",
              "isMenuOpen"
            ])}
            onIsMenuOpenChange={p.generateStateOnChangeProp($state, [
              "navbar",
              "isMenuOpen"
            ])}
          />

          <div className={classNames(projectcss.all, sty.freeBox__vB9)}>
            <div
              className={classNames(projectcss.all, sty.freeBox__zoEqj)}
              id={"home"}
            >
              <div className={classNames(projectcss.all, sty.columns__a7Wpx)}>
                <div className={classNames(projectcss.all, sty.column__jxi8B)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__nmXAr)}
                    direction={"left"}
                    triggerOnce={true}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xFVw0)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hs2U2
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__qkxOl
                          )}
                        >
                          {"Indonesia \nDigital Rupiah"}
                        </h2>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xXGvV
                          )}
                        >
                          {
                            "Inovasi Mata Uang Digital Nusantara untuk menghubungkan \ndunia digital dengan Rupiah anda"
                          }
                        </div>
                      </p.Stack>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vYncT
                        )}
                      >
                        <Button2
                          className={classNames(
                            "__wab_instance",
                            sty.button2__phul1
                          )}
                          endIcon={
                            <Icon38Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vM6PJ
                              )}
                              role={"img"}
                            />
                          }
                          link={"/whitepaper-25-May-2023.pdf"}
                          shape={"rounded"}
                          showStartIcon={true}
                          startIcon={
                            <GoogleDocsSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vxCiI
                              )}
                              role={"img"}
                            />
                          }
                          submitsForm={false}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wCz2E
                            )}
                          >
                            {"Download our Whitepaper"}
                          </div>
                        </Button2>
                        <Button2
                          className={classNames(
                            "__wab_instance",
                            sty.button2__ehw0L
                          )}
                          endIcon={
                            <Icon38Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__iOif8
                              )}
                              role={"img"}
                            />
                          }
                          link={"#about"}
                          shape={"rounded"}
                          startIcon={
                            <ChecksvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__nqjhb
                              )}
                              role={"img"}
                            />
                          }
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___77PAx
                            )}
                          >
                            {"Pelajari Selengkapnya ->"}
                          </div>
                        </Button2>
                      </p.Stack>
                    </p.Stack>
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__pkUaO)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__swtb7)}
                    direction={"right"}
                    triggerOnce={true}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lhkpQ)}
                    />
                  </Reveal>
                </div>
              </div>
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox___1Seb)}
            id={"about"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__yOjcJ)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__aqzXj)}
              >
                <div className={classNames(projectcss.all, sty.column___3Atbj)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fRwtX)}
                  >
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal__clfvY
                      )}
                      direction={"left"}
                      triggerOnce={true}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__joUr)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/iddr/images/indonesianMappng.png",
                          fullWidth: 780,
                          fullHeight: 349,
                          aspectRatio: undefined
                        }}
                      />
                    </Reveal>
                  </div>
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__sBMrx)}
                >
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__jy8R7)}
                    direction={"right"}
                    triggerOnce={true}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h4MuD)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__bswU
                        )}
                      >
                        {"Tentang Indonesia \nDigital Rupiah"}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tO4
                        )}
                      >
                        {
                          "Indonesia Digital Rupiah adalah mata uang digital terkini yang dirancang untuk mendukung kemajuan ekonomi dan teknologi di Indonesia. Menggabungkan keamanan, kecepatan, dan efisiensi blockchain dengan nilai dan stabilitas Rupiah, Indonesia Digital Rupiah menjadi solusi yang inovatif dalam era digital. Dengan menggunakan Indonesia Digital Rupiah, Anda dapat melakukan transaksi digital secara mudah, aman, dan cepat, baik dalam negeri maupun lintas batas. Bergabunglah dengan revolusi mata uang digital Indonesia dan rasakan kemudahan serta manfaatnya dalam kehidupan sehari-hari."
                        }
                      </div>
                    </div>
                  </Reveal>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__aNv5A)}
            id={"contract"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__c3I2J)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__s3Jve)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__y58C)}
                >
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__oeRkk)}
                    direction={"right"}
                    triggerOnce={true}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hwh23)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__uEgEx
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Smart Contract Indonesia \nDigital Rupiah "
                          : "Smart Contract \nIndonesia Digital Rupiah "}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bCvZ
                        )}
                      >
                        {
                          "Indonesia Digital Rupiah memberikan fleksibilitas dan ketersediaan melalui integrasi di berbagai platform blockchain terkemuka"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__z17C
                        )}
                      >
                        <h3
                          data-plasmic-name={"h3"}
                          data-plasmic-override={overrides.h3}
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3
                          )}
                        >
                          {"300.000.000 IDDR"}
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cymz
                          )}
                        >
                          {"Circulating supply"}
                        </div>
                      </div>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lZfc9
                        )}
                      >
                        <NetworkCard
                          className={classNames(
                            "__wab_instance",
                            sty.networkCard__n9Ai3
                          )}
                        >
                          <p.Stack
                            as={p.PlasmicLink}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__l6O5Q
                            )}
                            component={Link}
                            href={
                              "https://etherscan.io/token/0x9a8284c2cec196478f01ef4446a0222dd4def00e"
                            }
                            platform={"nextjs"}
                            target={"_blank"}
                          >
                            <Icon4Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__skzEw
                              )}
                              role={"img"}
                            />

                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__aUu4S
                              )}
                            >
                              {"Ethereum"}
                            </h5>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__k19Go
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___7SC4Q
                                )}
                              >
                                {
                                  "https://etherscan.io/token/0x9a8284c2cec196478f01ef4446a0222dd4def00e"
                                }
                              </div>
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__br0Nq
                                )}
                                role={"img"}
                              />
                            </div>
                          </p.Stack>
                        </NetworkCard>
                        <NetworkCard
                          className={classNames(
                            "__wab_instance",
                            sty.networkCard__sg0Br
                          )}
                        >
                          <p.Stack
                            as={p.PlasmicLink}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__bBe0P
                            )}
                            component={Link}
                            href={
                              "https://www.bscscan.com/token/0x9a8284c2cec196478f01ef4446a0222dd4def00e"
                            }
                            platform={"nextjs"}
                            target={"_blank"}
                          >
                            <Icon3Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__mZ6Km
                              )}
                              role={"img"}
                            />

                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__oZmj0
                              )}
                            >
                              {"BSC"}
                            </h5>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ih0Sx
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___9Mr6
                                )}
                              >
                                {"https://bscscan.com/token/0x9a...f00e"}
                              </div>
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___4Uf8L
                                )}
                                role={"img"}
                              />
                            </div>
                          </p.Stack>
                        </NetworkCard>
                        <NetworkCard
                          className={classNames(
                            "__wab_instance",
                            sty.networkCard__piGP
                          )}
                        >
                          <p.Stack
                            as={p.PlasmicLink}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__hikkj
                            )}
                            component={Link}
                            href={
                              "https://polygonscan.com/token/0x9a8284c2cec196478f01ef4446a0222dd4def00e"
                            }
                            platform={"nextjs"}
                            target={"_blank"}
                          >
                            <Icon5Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ji7Nd
                              )}
                              role={"img"}
                            />

                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__yeSt
                              )}
                            >
                              {"Polygon"}
                            </h5>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__iVmVy
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__reNf9
                                )}
                              >
                                {"https://polygonscan.com/token/0x9a...f00e"}
                              </div>
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__e4Ja2
                                )}
                                role={"img"}
                              />
                            </div>
                          </p.Stack>
                        </NetworkCard>
                      </p.Stack>
                    </div>
                  </Reveal>
                </p.Stack>
                <div className={classNames(projectcss.all, sty.column__abTQl)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9TUHz)}
                  >
                    <Reveal
                      className={classNames(
                        "__wab_instance",
                        sty.reveal___1VFEj
                      )}
                      direction={"left"}
                      triggerOnce={true}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__syY7)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/iddr/images/smartcontract3Png.png",
                          fullWidth: 1024,
                          fullHeight: 1024,
                          aspectRatio: undefined
                        }}
                      />
                    </Reveal>
                  </div>
                </div>
              </p.Stack>
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__aO8ZD)}
            id={"team"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__u44ZL)}>
              <Reveal
                className={classNames("__wab_instance", sty.reveal__a6UTc)}
                direction={"up"}
                triggerOnce={true}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.title)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___8Z9W
                    )}
                  >
                    {"Tim kami"}
                  </h2>
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__xEvGy
                    )}
                  >
                    {
                      "Kami bekerja dengan pengalaman dan keahlian terbaik di industri keuangan."
                    }
                  </h6>
                </p.Stack>
              </Reveal>
              <Reveal
                className={classNames("__wab_instance", sty.reveal__yDdRl)}
                direction={"up"}
                triggerOnce={true}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__gWgGi)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__cWWzc)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__uoVx)}
                      displayHeight={"200px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/iddr/images/fandy3Png.png",
                        fullWidth: 800,
                        fullHeight: 800,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      data-plasmic-name={"desc"}
                      data-plasmic-override={overrides.desc}
                      className={classNames(projectcss.all, sty.desc)}
                    >
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__x3J1W
                        )}
                      >
                        {"Fandy Label Honggono"}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__x2GMl
                        )}
                      >
                        {"CEO"}
                      </div>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__exXk1)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__obYqS)}
                      displayHeight={"200px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/iddr/images/janepng.png",
                        fullWidth: 550,
                        fullHeight: 551,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      data-plasmic-name={"desc2"}
                      data-plasmic-override={overrides.desc2}
                      className={classNames(projectcss.all, sty.desc2)}
                    >
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__wDsiE
                        )}
                      >
                        {"Jane Malinda Sutanto"}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pDx96
                        )}
                      >
                        {"CFO"}
                      </div>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__dDnKp)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__bCni)}
                      displayHeight={"200px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/iddr/images/yulipng.png",
                        fullWidth: 638,
                        fullHeight: 638,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      data-plasmic-name={"desc3"}
                      data-plasmic-override={overrides.desc3}
                      className={classNames(projectcss.all, sty.desc3)}
                    >
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6___0Y1Yz
                        )}
                      >
                        {"Liem Yuliana"}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ovf1K
                        )}
                      >
                        {"Finance Advisor"}
                      </div>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__zEpn)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___4UDsR)}
                      displayHeight={"200px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/iddr/images/willypng.png",
                        fullWidth: 1200,
                        fullHeight: 1200,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      data-plasmic-name={"desc4"}
                      data-plasmic-override={overrides.desc4}
                      className={classNames(projectcss.all, sty.desc4)}
                    >
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__d3Qgw
                        )}
                      >
                        {"Willyanto Wijaya S"}
                      </h6>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nqwbo
                        )}
                      >
                        {"Technical Advisor"}
                      </div>
                    </div>
                  </p.Stack>
                </p.Stack>
              </Reveal>
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__yYrZu)}
            id={"bank"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__adpNo)}>
              <Reveal
                className={classNames("__wab_instance", sty.reveal__ifIpE)}
                direction={"up"}
                triggerOnce={true}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"title3"}
                  data-plasmic-override={overrides.title3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.title3)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__n0USz
                    )}
                  >
                    {"Laporan Bulanan Bank"}
                  </h2>
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__aE9DA
                    )}
                  >
                    {"Laporan Bulanan Bank Indonesia Digital Rupiah"}
                  </h6>
                </p.Stack>
              </Reveal>
              <DataProvider
                data-plasmic-name={"dataProvider"}
                data-plasmic-override={overrides.dataProvider}
                className={classNames("__wab_instance", sty.dataProvider)}
                data={[
                  {
                    id: 1,
                    desc: "Indonesia Digital Rupiah Bank Report - Jan 2023",
                    date: "Last Updated, 1 January 2023",
                    url: ["https://www.fillmurray.com/200/300"]
                  },
                  {
                    id: 2,
                    desc: "Indonesia Digital Rupiah Bank Report - Feb 2023",
                    date: "Last Updated, 1 February 2023",
                    url: ["https://www.fillmurray.com/200/300"]
                  },
                  {
                    id: 3,
                    desc: "Indonesia Digital Rupiah Bank Report - Mar 2023",
                    date: "Last Updated, 1 March 2023",
                    url: ["https://www.fillmurray.com/200/300"]
                  },
                  {
                    id: "1",
                    desc: "Indonesia Digital Rupiah Bank Report - Apr 2023",
                    date: "Last Updated, 1 April 2023",
                    url: ["https://www.fillmurray.com/200/300"]
                  },
                  {
                    id: "1",
                    desc: "Indonesia Digital Rupiah Bank Report - May 2023",
                    date: "Last Updated, 1 May 2023",
                    url: ["https://www.fillmurray.com/200/300"]
                  },
                  {
                    id: "2",
                    desc: "Indonesia Digital Rupiah Bank Report - Jun 2023",
                    date: "Last Updated, 1 June 2023",
                    url: ["https://www.placecage.com/200/300"]
                  }
                ]}
                name={"bankReport"}
              >
                <ph.DataCtxReader>
                  {$ctx => (
                    <RichList
                      data-plasmic-name={"dataList"}
                      data-plasmic-override={overrides.dataList}
                      bordered={false}
                      className={classNames("__wab_instance", sty.dataList)}
                      content={(() => {
                        const __composite = [
                          { role: "content", fieldId: null, isHidden: null }
                        ];
                        __composite["0"]["fieldId"] = "date";
                        __composite["0"]["isHidden"] = false;
                        return __composite;
                      })()}
                      data={(() => {
                        try {
                          return $ctx.bankReport;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      hideSearch={true}
                      image={(() => {
                        const __composite = { fieldId: null, expr: null };
                        __composite["fieldId"] = "";
                        __composite["expr"] = (currentItem, currentValue) => {
                          return "https://iddr-dev-wheat.vercel.app/plasmic/iddr/images/documentIconpng.png";
                        };
                        return __composite;
                      })()}
                      linkTo={currentItem => {
                        return currentItem.url[0];
                      }}
                      pageSize={5}
                      pagination={true}
                      rowActions={[]}
                      title={(() => {
                        const __composite = [{ role: "title", fieldId: null }];
                        __composite["0"]["fieldId"] = "desc";
                        return __composite;
                      })()}
                      type={"list"}
                    />
                  )}
                </ph.DataCtxReader>
              </DataProvider>
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__dAw1O)}
            id={"contact"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__lcmS1)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__vDqJ9)}
              >
                <div className={classNames(projectcss.all, sty.column__jtIQ)}>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"title2"}
                    data-plasmic-override={overrides.title2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.title2)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__o65N1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5L0Fg
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#FFFDFD" }}
                          >
                            {"Supervised by"}
                          </span>
                        </React.Fragment>
                      </div>
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___52WA5)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"300px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/iddr/images/bappebtiRemovebpng2.png",
                          fullWidth: 432,
                          fullHeight: 137,
                          aspectRatio: undefined
                        }}
                      />
                    </p.Stack>
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__h17U4
                      )}
                    >
                      {"Kontak"}
                    </h2>
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__dLzMm
                      )}
                    >
                      {"Let\u2019s Work Together"}
                    </h6>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__exB6N
                      )}
                    >
                      {
                        "JL. Jend. Sudirman Kav 21, Kel. Karet Kuningan, Kec. Setiabudi, Jakarta Selatan, DKI Jakarta, Indonesia 12920\n\ninfo@iddr.io"
                      }
                    </div>
                  </p.Stack>
                </div>
                <div className={classNames(projectcss.all, sty.column__haRrA)}>
                  <Embed
                    data-plasmic-name={"embedHtml"}
                    data-plasmic-override={overrides.embedHtml}
                    className={classNames("__wab_instance", sty.embedHtml)}
                    code={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15865.606422642355!2d106.8222893!3d-6.2106448!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f55e2d3fbe1f%3A0x9a3af0621b70d07f!2sWeWork%20Sinarmas%20MSIG%20Tower!5e0!3m2!1sen!2sid!4v1684983001341!5m2!1sen!2sid" width="360" height="460" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
                        : '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15865.606422642355!2d106.8222893!3d-6.2106448!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f55e2d3fbe1f%3A0x9a3af0621b70d07f!2sWeWork%20Sinarmas%20MSIG%20Tower!5e0!3m2!1sen!2sid!4v1684983001341!5m2!1sen!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
                    }
                  />
                </div>
              </p.Stack>
            </div>
          </div>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__tk5Ht)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__niorR)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uwzXi
                )}
              >
                {"\u00a9 2023 by Indonesia Digital Rupiah"}
              </div>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__y0C9B)}
              >
                <p.PlasmicLink
                  data-plasmic-name={"cmc"}
                  data-plasmic-override={overrides.cmc}
                  className={classNames(projectcss.all, projectcss.a, sty.cmc)}
                  component={Link}
                  href={"https://coinmarketcap.com/currencies/idr-digital/"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <CmcsvgIcon
                    className={classNames(projectcss.all, sty.svg__bBfyP)}
                    role={"img"}
                  />
                </p.PlasmicLink>
                <p.PlasmicLink
                  data-plasmic-name={"telegram"}
                  data-plasmic-override={overrides.telegram}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.telegram
                  )}
                  component={Link}
                  href={"https://t.me/iddr_io"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <IconIcon
                    className={classNames(projectcss.all, sty.svg__asEhz)}
                    role={"img"}
                  />
                </p.PlasmicLink>
                <p.PlasmicLink
                  data-plasmic-name={"twitter"}
                  data-plasmic-override={overrides.twitter}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.twitter
                  )}
                  component={Link}
                  href={"https://twitter.com/iddr_io"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <Icon2Icon
                    className={classNames(projectcss.all, sty.svg__bkLqu)}
                    role={"img"}
                  />
                </p.PlasmicLink>
              </p.Stack>
            </div>
          </p.Stack>
          {(
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? (() => {
                  try {
                    return $state.navbar.isMenuOpen;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })()
              : (() => {
                  try {
                    return $state.navbar.isMenuOpen;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })()
          ) ? (
            <MenuOverlay
              data-plasmic-name={"menuOverlay"}
              data-plasmic-override={overrides.menuOverlay}
              className={classNames("__wab_instance", sty.menuOverlay)}
              slot={
                <Button2
                  className={classNames("__wab_instance", sty.button2__bNeGi)}
                  color={"clear"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__wa2G5)}
                      role={"img"}
                    />
                  }
                  link={"#home"}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateNavbarIsMenuOpen"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["navbar", "isMenuOpen"]
                            },
                            operation: 4
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      typeof $steps["updateNavbarIsMenuOpen"] === "object" &&
                      typeof $steps["updateNavbarIsMenuOpen"].then ===
                        "function"
                    ) {
                      $steps["updateNavbarIsMenuOpen"] = await $steps[
                        "updateNavbarIsMenuOpen"
                      ];
                    }
                  }}
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__t9Xdm)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kkldl
                    )}
                  >
                    {"Beranda"}
                  </div>
                </Button2>
              }
              slot2={
                <Button2
                  className={classNames("__wab_instance", sty.button2__xFq2E)}
                  color={"clear"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__k7YTd)}
                      role={"img"}
                    />
                  }
                  link={"#about"}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateNavbarIsMenuOpen"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["navbar", "isMenuOpen"]
                            },
                            operation: 4
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      typeof $steps["updateNavbarIsMenuOpen"] === "object" &&
                      typeof $steps["updateNavbarIsMenuOpen"].then ===
                        "function"
                    ) {
                      $steps["updateNavbarIsMenuOpen"] = await $steps[
                        "updateNavbarIsMenuOpen"
                      ];
                    }
                  }}
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg___8FBP)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v6BfB
                    )}
                  >
                    {"Tentang"}
                  </div>
                </Button2>
              }
              slot3={
                <Button2
                  className={classNames("__wab_instance", sty.button2__bKkjH)}
                  color={"clear"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__aL24D)}
                      role={"img"}
                    />
                  }
                  link={"#team"}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateNavbarIsMenuOpen"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["navbar", "isMenuOpen"]
                            },
                            operation: 4
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      typeof $steps["updateNavbarIsMenuOpen"] === "object" &&
                      typeof $steps["updateNavbarIsMenuOpen"].then ===
                        "function"
                    ) {
                      $steps["updateNavbarIsMenuOpen"] = await $steps[
                        "updateNavbarIsMenuOpen"
                      ];
                    }
                  }}
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__nttXz)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vnY7U
                    )}
                  >
                    {"Tim"}
                  </div>
                </Button2>
              }
              slot4={
                <Button2
                  className={classNames("__wab_instance", sty.button2__nzTzT)}
                  color={"clear"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__rmG2C)}
                      role={"img"}
                    />
                  }
                  link={"#contact"}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateNavbarIsMenuOpen"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["navbar", "isMenuOpen"]
                            },
                            operation: 4
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      typeof $steps["updateNavbarIsMenuOpen"] === "object" &&
                      typeof $steps["updateNavbarIsMenuOpen"].then ===
                        "function"
                    ) {
                      $steps["updateNavbarIsMenuOpen"] = await $steps[
                        "updateNavbarIsMenuOpen"
                      ];
                    }
                  }}
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__d81Vk)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pot9A
                    )}
                  >
                    {"Kontak"}
                  </div>
                </Button2>
              }
            >
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__a9M7
                )}
                component={Link}
                onClick={async event => {
                  const $steps = {};
                  $steps["updateNavbarIsMenuOpen"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["navbar", "isMenuOpen"]
                          },
                          operation: 4
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          const oldValue = p.get(objRoot, variablePath);
                          p.set(objRoot, variablePath, !oldValue);
                          return !oldValue;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    typeof $steps["updateNavbarIsMenuOpen"] === "object" &&
                    typeof $steps["updateNavbarIsMenuOpen"].then === "function"
                  ) {
                    $steps["updateNavbarIsMenuOpen"] = await $steps[
                      "updateNavbarIsMenuOpen"
                    ];
                  }
                }}
                platform={"nextjs"}
              >
                <CloseBoldSvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg__m6LrQ)}
                  role={"img"}
                />
              </p.PlasmicLink>
            </MenuOverlay>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageMetadataOverride",
    "navbar",
    "h3",
    "title",
    "desc",
    "desc2",
    "desc3",
    "desc4",
    "title3",
    "dataProvider",
    "dataList",
    "title2",
    "embedHtml",
    "cmc",
    "telegram",
    "twitter",
    "menuOverlay"
  ],
  pageMetadataOverride: ["pageMetadataOverride"],
  navbar: ["navbar"],
  h3: ["h3"],
  title: ["title"],
  desc: ["desc"],
  desc2: ["desc2"],
  desc3: ["desc3"],
  desc4: ["desc4"],
  title3: ["title3"],
  dataProvider: ["dataProvider", "dataList"],
  dataList: ["dataList"],
  title2: ["title2"],
  embedHtml: ["embedHtml"],
  cmc: ["cmc"],
  telegram: ["telegram"],
  twitter: ["twitter"],
  menuOverlay: ["menuOverlay"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageMetadataOverride: typeof PlasmicHead;
  navbar: typeof Navbar;
  h3: "h3";
  title: "div";
  desc: "div";
  desc2: "div";
  desc3: "div";
  desc4: "div";
  title3: "div";
  dataProvider: typeof DataProvider;
  dataList: typeof RichList;
  title2: "div";
  embedHtml: typeof Embed;
  cmc: "a";
  telegram: "a";
  twitter: "a";
  menuOverlay: typeof MenuOverlay;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    navbar: makeNodeComponent("navbar"),
    h3: makeNodeComponent("h3"),
    title: makeNodeComponent("title"),
    desc: makeNodeComponent("desc"),
    desc2: makeNodeComponent("desc2"),
    desc3: makeNodeComponent("desc3"),
    desc4: makeNodeComponent("desc4"),
    title3: makeNodeComponent("title3"),
    dataProvider: makeNodeComponent("dataProvider"),
    dataList: makeNodeComponent("dataList"),
    title2: makeNodeComponent("title2"),
    embedHtml: makeNodeComponent("embedHtml"),
    cmc: makeNodeComponent("cmc"),
    telegram: makeNodeComponent("telegram"),
    twitter: makeNodeComponent("twitter"),
    menuOverlay: makeNodeComponent("menuOverlay"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
